### ISSUE TITLE
remove docker installation instructions

### ISSUE THREAD

**Issue by npalm** [uribench/software-engineering-handbook#15]
In software engineering the DRY principle is pretty well known. We should avoid code duplication / copy paste behaviour. Our static code analysers check typically for this anti-pattern. So why would we reproduce documentation how to install docker. It is a waste of energy which we can put in building great software. Also it will be hard to maintain. The documentation by docker is good, complete and well maintained. So I suggest to remove installation details and just refer to docker.

**Comment by uribench** [comment]
In general and for obvious reasons, we try not to duplicate content that is available elsewhere. However, there are few exceptions, and this is one of them. The quality of the documentation by docker is questionable. Here we have decided to provide a short installation description along with a link to a separated longer version annotating some of the less trivial steps. One can always skip the elaborated description and refer directly to the original installation instructions that is always provided. Nevertheless, I am considering to make the shorter version even shorter, as you have suggested, but keep the additional annotated version for people that are interested in details that are not available by docker.
