### ISSUE TITLE
Choose a Jekyll theme for the site

### ISSUE THREAD

**Issue by DannyBen** [uribench/software-engineering-handbook#3]
In order for the site to be ready for prime time, I suggest allocating some time to choosing (or making) a proper Jekyll theme.

The implementation options are (easiest first):

1. Just choose one of the [supported themes][supported-themes], without customizing anything.
2. Choose one of the themes, and add some lightweight customization to it through a [Jekyll config file, and/or custom CSS and/or layout HTML][customization].
3. Find a [community-contributed Jekyll theme][external-themes], compatible with GitHub Pages.
4. Clone one of the supported themes, and [create our own][create-theme], completely custom theme.

Option 4, being the most time consuming to implement, *may* give us the option to add completely custom elements, such as an automatically generated breadcrumbs header, for example.

[supported-themes]: https://pages.github.com/themes/
[customization]: https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/
[external-themes]: https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/
[create-theme]: https://jekyllrb.com/docs/themes/

**Comment by uribench** [comment]
Selected 'jekyll-theme-cayman' theme and customized it lightly
